feat(web3mail): Add API routes for storage ability
Torof/LedgityYield pull request #1
Opened 2024-06-28 08:48 UTC by cyrilcolinet

2024-06-29 07:00 UTC, Torof requested changes
j'ai refactorisé le code pour qu'il fonctionne, qu'il soit plus accessible et lisible.

Les deux files ajoutées ça va passer mais pas le code ajouté, parceque j'ai changé des noms de fonctions , enlevé des usestate et modifié un peu les fonctions

2024-07-01 15:37 UTC, cyrilcolinet commented
@Torof okay, si jamais tu peux juste prendre les deux fichiers dans `/api` et après dans les components (`.tsx`), tu peux facilement réutiliser la partie que j'ai ajouté.

Après si besoin, je mets à jour avec ta branch et je te résoud les conflits ?

2024-07-02 01:30 UTC, Torof approved these changes
super, ces deux files sont nickel, je vais pouvoir intégrer facilement avec le front

2024-07-02 01:31 UTC, Torof commented
C'est tout bon, j'ai enlevé les ajouts dans les components, et acceptés les deux routers, ce sera plus facile pour éviter les bugs et continuer de maintenir et ajouter

2024-07-02 01:32 UTC, merged